apiVersion: v1
kind: Namespace
metadata:
  name: analytics

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: analytics
  name: business-analyst
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: business-analyst-binding
  namespace: analytics
subjects:
- kind: User
  name: business-analyst
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: business-analyst
  apiGroup: rbac.authorization.k8s.io