---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-home

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: smart-home
  name: product-owner
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: product-owner-binding
  namespace: smart-home
subjects:
- kind: User
  name: product-owner
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: product-owner
  apiGroup: rbac.authorization.k8s.io