apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: support-engineer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "events"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: support-engineer-binding
  namespace: production
subjects:
- kind: User
  name: support-engineer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: support-engineer
  apiGroup: rbac.authorization.k8s.io